#!/bin/sh /etc/rc.common

START=99
USE_PROCD=1
PROG=/usr/sbin/wol-mqtt

start_service() {
        procd_open_instance
        procd_set_param command $PROG -b=<broker> <topic>
        procd_set_param stderr 1
        procd_set_param stdout 1
        procd_close_instance
}